name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main  # Change this to your branch if needed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install Firebase CLI
      run: npm install -g firebase-tools

    - name: Authenticate with Firebase
      run: firebase use --add sigai-backend --token "${{ secrets.FIREBASE_TOKEN }}"

    - name: Deploy to Firebase
      run: firebase deploy --token "${{ secrets.FIREBASE_TOKEN }}"
