// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgtGoGftagaOAzb9f5CjPCQpf5ffLp-8k',
    appId: '1:341686309422:web:3111f9ad6ade07fa3d05bf',
    messagingSenderId: '341686309422',
    projectId: 'sigai-backend',
    authDomain: 'sigai-backend.firebaseapp.com',
    databaseURL: 'https://sigai-backend-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'sigai-backend.firebasestorage.app',
    measurementId: 'G-0DQKE0EJXV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnZ-yoAtjXKFSPLLDTL7mvwVCnp7UjnnI',
    appId: '1:341686309422:android:403704e30d006dd53d05bf',
    messagingSenderId: '341686309422',
    projectId: 'sigai-backend',
    databaseURL: 'https://sigai-backend-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'sigai-backend.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHVhGm_QX9zaGoafNt-lbEIsPVrJKgaRI',
    appId: '1:341686309422:ios:82040fb8278fa1833d05bf',
    messagingSenderId: '341686309422',
    projectId: 'sigai-backend',
    databaseURL: 'https://sigai-backend-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'sigai-backend.firebasestorage.app',
    iosBundleId: 'com.ainal.sigai',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBHVhGm_QX9zaGoafNt-lbEIsPVrJKgaRI',
    appId: '1:341686309422:ios:82040fb8278fa1833d05bf',
    messagingSenderId: '341686309422',
    projectId: 'sigai-backend',
    databaseURL: 'https://sigai-backend-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'sigai-backend.firebasestorage.app',
    iosBundleId: 'com.ainal.sigai',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDgtGoGftagaOAzb9f5CjPCQpf5ffLp-8k',
    appId: '1:341686309422:web:d1ad5c232a4f0e783d05bf',
    messagingSenderId: '341686309422',
    projectId: 'sigai-backend',
    authDomain: 'sigai-backend.firebaseapp.com',
    databaseURL: 'https://sigai-backend-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'sigai-backend.firebasestorage.app',
    measurementId: 'G-37HBRMJJFE',
  );
}
