name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18  # Use LTS version

      - name: Clean Install
        run: rm -rf node_modules package-lock.json && npm install
        
      - name: Install project dependencies
        run: npm ci

      - name: Install Firebase CLI Globally
        run: npm install -g firebase-tools

      - name: Authenticate with Firebase
        run: firebase login:ci --token "${{ secrets.FIREBASE_TOKEN }}"

      - name: Deploy to Firebase Hosting
        run: firebase deploy --only hosting
